INSERT INTO `guru` (`id`, `nama`, `aktif`) VALUES
(1, 'Dwi Anggraeni, S.Pd., M.Pd.', 1),
(2, 'Dra. Ririn Herawati, M.M.', 1),
(3, 'Ismail, S.Pd, M.M.', 1),
(4, 'Dra. Rosa Desiana, M.M.', 1),
(5, 'Dra. Sri Rahayu, M.M.', 1),
(6, 'Dra. Ninik Supriati', 1),
(7, 'Dra. Jajuk Surjaningtyas, M.M.', 1),
(8, 'Saiful Bahri, S.Pd, M.Pd', 1),
(9, 'Dra. Jetti Ernawati, M.M.', 1),
(10, 'Mu’arifia Ertiana, S.Pd.', 1),
(11, 'Dra. Wulandari, M.M.', 1),
(12, 'Tanti Indarwati, S.E, M.M.', 1),
(13, 'Tony Wahyudi Faisal, S.E. M.A.', 1),
(14, 'Dra. Lifi Kaulin, M.M.', 1),
(15, 'Dedy Ari Prihartono, S.Pd., M.Pd', 1),
(16, 'Yuni Hidayati, S.Pd. M.Pd.', 1),
(17, 'Masrifa Nuraini, S.Pd. M.M.', 1),
(18, 'Moh. Kohar, S.Kom.', 1),
(19, 'Yumani Andis Azizah, S.Pd. M.M.', 1),
(20, 'Titik Sugiharti, S.Pd.', 1),
(21, 'Ratih Puspita Dewi D.R, S.E.', 1),
(22, 'Edi Wiranto, S.E.', 1),
(23, 'Rini Widayati, S.Pd, M.M.', 1),
(24, 'Erni Setiyowati, S.Pd.', 1),
(25, 'Aning Ekowati, S.Kom.', 1),
(26, 'Suwandi, S.Pd.', 1),
(27, 'Sri Wahyuningsih, S.Pd.', 1),
(28, 'Nenny Dwiningtyas, S.Pd., M.Pd.', 1),
(29, 'Purwanti, S.E., M.Pd.', 1),
(30, 'Indah Fajarwati, S.Pd., M.Pd.', 1),
(31, 'Yeny Galuh BK, S.Pd., M.M.', 1),
(32, 'Widati, S.Pd., M.Pd.', 1),
(33, 'Siti Muslipa, S.Pd, M.M.', 1),
(34, 'Anita Prasasti, S.Pd, M.M.', 1),
(35, 'Gunaning Garjito, S.Pd.', 1),
(36, 'Eva Okta Triana, S.Psi.', 1),
(37, 'Ida Marhaeningsih, S.Pd.', 1),
(38, 'Nanang Subagiyo, S.Pd.', 1),
(39, 'Anang Jasmiko, S.T.', 1),
(40, 'Nanik Sriawan, S.Pd.', 1),
(41, 'Ita Sulistyowati, S.Pd.', 1),
(42, 'Kartika Cahayawati, S.Pd.', 1),
(43, 'Arvind Cahyono, S.Pd.', 1),
(44, 'Inna, S.Pd. M.Pd.', 1),
(45, 'Lidya Trismiana, S.Pd.', 1),
(46, 'Anton Hartono, S.Kom.', 1),
(47, 'Sri Hartuti, S.Pd.', 1),
(48, 'Sensusiani Isriyati, S.Pd, M.Pd.', 1),
(49, 'Ali Afandi, S.Pd, M.Pd.', 1),
(50, 'Dwi Yuli Widyayanti, S.Pd, M.Pd.', 1),
(51, 'Prastowo Ismanto, S.Pd.', 1),
(52, 'Kinasih Dwijayanti, S.Pd.', 1),
(53, 'Aryadne Widiastuti, S.Pd.', 1),
(54, 'Aji Dharma Ertanto, S.Pd, M.Pd.', 1),
(55, 'Arif Hendro Waluyo, S.Pd.', 1),
(56, 'Wisnu Pebrianto, S.Pd.', 1),
(57, 'Muhammad Nur Affan, S.Kom.', 1),
(58, 'Silfiya Ilma Rosida, S.Pd., Gr', 1),
(59, 'Aida Jamila, S.Pd', 1),
(60, 'Dheny Rahmayanti, S.E', 1),
(61, 'Asfiainnisa, S.Pd, Gr', 1),
(62, 'Lailatul Jannah, S.Pd.', 1),
(63, 'Nanditia Widiasmara, S.Pd.', 1),
(64, 'Sonie Setyawan, S.Pd.', 1),
(65, 'Elinda Rukmana, S.Pd.', 1),
(66, 'Sitta Setyoningsih, S.Pd.', 1),
(67, 'Muhammad Samsul Arifin, S.Pd., M.Pd', 1),
(68, 'Pujo Dwi Nugroho, S.Pd.', 1),
(69, 'Yaumul Sya’ban Wahyu P, S.Pd.', 1),
(70, 'Wahyu Budi Setya Agung, S.Pd', 1),
(71, 'Lya Dillya Rahayu, S.Pd', 1),
(72, 'Putri Utamining LA, S.Pd.', 1),
(73, 'Mohammad Nurhamsalim, S.Pd', 1),
(74, 'Ahmad Farisi, S.PdI', 1),
(75, 'Isti Ainurrahma, S.Pd', 1),
(76, 'Rieska Tri Wulandari, S.Pd', 1),
(77, 'Nur Anisa Citra Devi, S.Kom', 1),
(78, 'Mustamrin, S.Th.', 1),
(79, 'Dyah Yuliati, S.Pd.', 1),
(80, 'Febri Nia Saritha, S.Pd.', 1),
(81, 'Desi Wulandari, S.Pd.', 1),
(82, 'Ahmad Syaifi R M, S.Pd.', 1),
(83, 'Ahmad Fauzan, S.Pdi', 1),
(84, 'Shinata Putra, S.Pd', 1),
(85, 'Fivika Amanah Novianti, S.Psi', 1),
(86, 'Suhartono, S.Pdi', 1),
(87, 'Rahardi Teguh Prakoso, S.Pd', 1),
(88, 'Dino Purbo Cahyanto, S.Pd', 1),
(89, 'Erina Dwiky Anggraeni, S.Pd', 1);
